# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: handshake.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhandshake.proto\x12\rpywhats.proto\"\x94\x03\n\x10HandshakeMessage\x12\x41\n\x0c\x63lient_hello\x18\x02 \x01(\x0b\x32+.pywhats.proto.HandshakeMessage.ClientHello\x12\x41\n\x0cserver_hello\x18\x03 \x01(\x0b\x32+.pywhats.proto.HandshakeMessage.ServerHello\x12\x43\n\rclient_finish\x18\x04 \x01(\x0b\x32,.pywhats.proto.HandshakeMessage.ClientFinish\x1a\x41\n\x0b\x43lientHello\x12\x11\n\tephemeral\x18\x01 \x01(\x0c\x12\x0e\n\x06static\x18\x02 \x01(\x0c\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a\x41\n\x0bServerHello\x12\x11\n\tephemeral\x18\x01 \x01(\x0c\x12\x0e\n\x06static\x18\x02 \x01(\x0c\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x1a/\n\x0c\x43lientFinish\x12\x0e\n\x06static\x18\x01 \x01(\x0c\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKEMESSAGE']._serialized_start=35
  _globals['_HANDSHAKEMESSAGE']._serialized_end=439
  _globals['_HANDSHAKEMESSAGE_CLIENTHELLO']._serialized_start=258
  _globals['_HANDSHAKEMESSAGE_CLIENTHELLO']._serialized_end=323
  _globals['_HANDSHAKEMESSAGE_SERVERHELLO']._serialized_start=325
  _globals['_HANDSHAKEMESSAGE_SERVERHELLO']._serialized_end=390
  _globals['_HANDSHAKEMESSAGE_CLIENTFINISH']._serialized_start=392
  _globals['_HANDSHAKEMESSAGE_CLIENTFINISH']._serialized_end=439
# @@protoc_insertion_point(module_scope)
