# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: history_sync.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'history_sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12history_sync.proto\x12\rpywhats.proto\"\x9a\x03\n\x0bHistorySync\x12\x42\n\tsync_type\x18\x01 \x01(\x0e\x32*.pywhats.proto.HistorySync.HistorySyncTypeH\x00\x88\x01\x01\x12\x32\n\rconversations\x18\x02 \x03(\x0b\x32\x1b.pywhats.proto.Conversation\x12\x18\n\x0b\x63hunk_order\x18\x05 \x01(\rH\x01\x88\x01\x01\x12\x15\n\x08progress\x18\x06 \x01(\rH\x02\x88\x01\x01\x12*\n\tpushnames\x18\x07 \x03(\x0b\x32\x17.pywhats.proto.Pushname\"\x8a\x01\n\x0fHistorySyncType\x12\x15\n\x11INITIAL_BOOTSTRAP\x10\x00\x12\x15\n\x11INITIAL_STATUS_V3\x10\x01\x12\x08\n\x04\x46ULL\x10\x02\x12\n\n\x06RECENT\x10\x03\x12\r\n\tPUSH_NAME\x10\x04\x12\x15\n\x11NON_BLOCKING_DATA\x10\x05\x12\r\n\tON_DEMAND\x10\x06\x42\x0c\n\n_sync_typeB\x0e\n\x0c_chunk_orderB\x0b\n\t_progress\"\xd7\x01\n\x0c\x43onversation\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12/\n\x08messages\x18\x02 \x03(\x0b\x32\x1d.pywhats.proto.HistorySyncMsg\x12\x11\n\x04name\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x1f\n\x12last_msg_timestamp\x18\x05 \x01(\x04H\x02\x88\x01\x01\x12\x19\n\x0cunread_count\x18\x06 \x01(\rH\x03\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_nameB\x15\n\x13_last_msg_timestampB\x0f\n\r_unread_count\"^\n\x0eHistorySyncMsg\x12\x14\n\x07message\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x19\n\x0cmsg_order_id\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\n\n\x08_messageB\x0f\n\r_msg_order_id\"F\n\x08Pushname\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08pushname\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x0b\n\t_pushnameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'history_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HISTORYSYNC']._serialized_start=38
  _globals['_HISTORYSYNC']._serialized_end=448
  _globals['_HISTORYSYNC_HISTORYSYNCTYPE']._serialized_start=267
  _globals['_HISTORYSYNC_HISTORYSYNCTYPE']._serialized_end=405
  _globals['_CONVERSATION']._serialized_start=451
  _globals['_CONVERSATION']._serialized_end=666
  _globals['_HISTORYSYNCMSG']._serialized_start=668
  _globals['_HISTORYSYNCMSG']._serialized_end=762
  _globals['_PUSHNAME']._serialized_start=764
  _globals['_PUSHNAME']._serialized_end=834
# @@protoc_insertion_point(module_scope)
