# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sender_key.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'sender_key.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10sender_key.proto\x12\rpywhats.proto\"|\n\x14SenderKeyMessageBody\x12\x0f\n\x02id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\titeration\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x17\n\nciphertext\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x42\x05\n\x03_idB\x0c\n\n_iterationB\r\n\x0b_ciphertext\"\xb0\x01\n SenderKeyDistributionMessageBody\x12\x0f\n\x02id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\titeration\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x16\n\tchain_key\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x12\x18\n\x0bsigning_key\x18\x04 \x01(\x0cH\x03\x88\x01\x01\x42\x05\n\x03_idB\x0c\n\n_iterationB\x0c\n\n_chain_keyB\x0e\n\x0c_signing_keyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sender_key_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDERKEYMESSAGEBODY']._serialized_start=35
  _globals['_SENDERKEYMESSAGEBODY']._serialized_end=159
  _globals['_SENDERKEYDISTRIBUTIONMESSAGEBODY']._serialized_start=162
  _globals['_SENDERKEYDISTRIBUTIONMESSAGEBODY']._serialized_end=338
# @@protoc_insertion_point(module_scope)
